services:
  postgres:
    image: "postgis/postgis:18-3.6-alpine"
    container_name: PetRadarDB
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data_db:/var/lib/postgresql
    platform: linux/amd64

  redis:
    image: "redis:8-alpine"
    container_name: PetRadarRedis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PetRadarApp
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - MAILER_EMAIL=${MAILER_EMAIL}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SERVICE=${MAILER_SERVICE}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APPINSIGHTS_CONNECTION_STRING=${APPINSIGHTS_CONNECTION_STRING}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data_db:
  redis_data:
